language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - if [[ "$CC" == "clang" ]]; then CFLAGS="-Weverything -Wpedantic -Wno-cast-qual" make ; fi
  - if [[ "$CC" == "gcc"   ]]; then CFLAGS=-Wpedantic make                               ; fi

script:
  - make test
